### ISSUE TITLE
ENABLE THE GH PAGES FOR RWPO

### ISSUE THREAD

**Issue by SGI-CAPP-AT2** [prasantkumar123/harrypotter.github.io#1]
# @prasantkumar123 
you are trying to host it but it will work after only you enable the GitHub pages from repo>settings
>Great project

**Comment by prasantkumar123** [comment]
@SGI-CAPP-AT2  Thank you
I have already hosted it.

**Comment by prasantkumar123** [comment]
GitHub page is already set to master branch. 
Thank you
